### ISSUE TITLE
As a Mentor / Mentee in the apply process, users are unable to open the PDF documents

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#688]
**Describe the bug**
Users are not able to open the PDF documents after application process, and application approved by Admin

**To Reproduce**
1) Apply as Mentor user
2) Approve the application as Admin user
3) As a mentor user, go to application page, get the training page opened
4) Try to open any PDF document in the training page

**Expected behavior**
PDF document must be opened, error happening is that clicking the PDF document button, nothing happens

**Screenshots/logs**

```
2023-04-16T23:35:39.666573+00:00 heroku[router]: at=info method=GET path="/api/application/checkConfirm/robertmurer+mentor160423@gmail.com/2" host=mentee-dev.herokuapp.com request_id=c4b39816-0f15-49b9-908a-4c8ec8e43fe9 fwd="181.165.121.110" dyno=web.1 connect=0ms service=4ms status=200 bytes=324 protocol=https
2023-04-16T23:35:42.083622+00:00 heroku[router]: at=info method=GET path="/api/application/checkHaveAccount/robertmurer+mentor160423@gmail.com/1" host=mentee-dev.herokuapp.com request_id=6536cf0e-ad8b-4240-8ba6-ec3a98c40284 fwd="181.165.121.110" dyno=web.1 connect=0ms service=142ms status=200 bytes=252 protocol=https
2023-04-16T23:35:42.082759+00:00 app[web.1]: 10.1.30.196 - - [16/Apr/2023:23:35:42 +0000] "GET /api/application/checkHaveAccount/robertmurer+mentor160423@gmail.com/1 HTTP/1.1" 200 75 "https://mentee-dev.herokuapp.com/application-page" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15"
2023-04-16T23:35:42.295673+00:00 app[web.1]: 10.1.30.196 - - [16/Apr/2023:23:35:42 +0000] "GET /api/application/checkConfirm/robertmurer+mentor160423@gmail.com/1 HTTP/1.1" 200 60 "https://mentee-dev.herokuapp.com/application-page" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15"
2023-04-16T23:35:42.296129+00:00 heroku[router]: at=info method=GET path="/api/application/checkConfirm/robertmurer+mentor160423@gmail.com/1" host=mentee-dev.herokuapp.com request_id=37ac29a4-d70e-419d-ac55-0152eb3df491 fwd="181.165.121.110" dyno=web.1 connect=0ms service=5ms status=200 bytes=237 protocol=https
2023-04-16T23:35:42.512748+00:00 heroku[router]: at=info method=GET path="/api/training/1" host=mentee-dev.herokuapp.com request_id=5e26dedf-1b22-441a-9351-aaafdcee2985 fwd="181.165.121.110" dyno=web.1 connect=0ms service=4ms status=200 bytes=1743 protocol=https
2023-04-16T23:35:42.512288+00:00 app[web.1]: 10.1.30.196 - - [16/Apr/2023:23:35:42 +0000] "GET /api/training/1 HTTP/1.1" 200 1564 "https://mentee-dev.herokuapp.com/application-page" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15"
2023-04-16T23:35:55.072762+00:00 heroku[router]: at=info method=GET path="/api/training/trainVideo/627d2b792720b6ebf28512dc" host=mentee-dev.herokuapp.com request_id=c8776e75-3b82-4c9c-929a-09d1cd5d5d53 fwd="181.165.121.110" dyno=web.1 connect=0ms service=2ms status=500 bytes=308 protocol=https
2023-04-16T23:35:55.071458+00:00 app[web.1]: [2023-04-16 23:35:55,071] INFO in require_auth: Error parsing JWT token -- not included in header or invalid token
2023-04-16T23:35:55.071480+00:00 app[web.1]: [2023-04-16 23:35:55 +0000] [8] [INFO] Error parsing JWT token -- not included in header or invalid token
2023-04-16T23:35:55.071630+00:00 app[web.1]: 2023-04-16 23:35:55,071 10.1.30.196: requested https://mentee-dev.herokuapp.com/api/training/trainVideo/627d2b792720b6ebf28512dc: INFO in [require_auth: 22]: Error parsing JWT token -- not included in header or invalid token
2023-04-16T23:35:55.071697+00:00 app[web.1]: [2023-04-16 23:35:55,071] INFO in require_auth: Illegal ID token provided: None. ID token must be a non-empty string.
2023-04-16T23:35:55.071722+00:00 app[web.1]: [2023-04-16 23:35:55 +0000] [8] [INFO] Illegal ID token provided: None. ID token must be a non-empty string.
2023-04-16T23:35:55.071742+00:00 app[web.1]: 2023-04-16 23:35:55,071 10.1.30.196: requested https://mentee-dev.herokuapp.com/api/training/trainVideo/627d2b792720b6ebf28512dc: INFO in [require_auth: 23]: Illegal ID token provided: None. ID token must be a non-empty string.
2023-04-16T23:35:55.072301+00:00 app[web.1]: 10.1.30.196 - - [16/Apr/2023:23:35:55 +0000] "GET /api/training/trainVideo/627d2b792720b6ebf28512dc HTTP/1.1" 500 111 "https://mentee-dev.herokuapp.com/application-page" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15"
```

**Comment by robert-dm** [comment]
```
www-widgetapi.js:1122 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('https://mentee-dev.herokuapp.com').
q.sendMessage @ www-widgetapi.js:1122
xhr.js:247          GET https://mentee-dev.herokuapp.com/api/training/trainVideo/627d2b792720b6ebf28512dc 500 (INTERNAL SERVER ERROR)
(anonymous) @ xhr.js:247
xhr @ xhr.js:49
Bv @ dispatchRequest.js:51
value @ Axios.js:142
Xm.forEach.Qv.<computed> @ Axios.js:168
(anonymous) @ bind.js:5
(anonymous) @ api.js:15
u @ regeneratorRuntime.js:44
(anonymous) @ regeneratorRuntime.js:125
(anonymous) @ regeneratorRuntime.js:69
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:22
Promise.then (async)
r @ asyncToGenerator.js:12
s @ asyncToGenerator.js:22
(anonymous) @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:19
(anonymous) @ api.js:14
(anonymous) @ api.js:219
u @ regeneratorRuntime.js:44
(anonymous) @ regeneratorRuntime.js:125
(anonymous) @ regeneratorRuntime.js:69
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:22
(anonymous) @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:19
(anonymous) @ api.js:217
(anonymous) @ TrainingList.js:39
u @ regeneratorRuntime.js:44
(anonymous) @ regeneratorRuntime.js:125
(anonymous) @ regeneratorRuntime.js:69
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:22
(anonymous) @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:19
T @ button.js:197
Ie @ react-dom.production.min.js:54
ze @ react-dom.production.min.js:54
(anonymous) @ react-dom.production.min.js:55
Dr @ react-dom.production.min.js:105
Lr @ react-dom.production.min.js:106
(anonymous) @ react-dom.production.min.js:117
ul @ react-dom.production.min.js:274
Me @ react-dom.production.min.js:52
Ur @ react-dom.production.min.js:109
Kt @ react-dom.production.min.js:74
Wt @ react-dom.production.min.js:73
Jm {message: 'Request failed with status code 500', name: 'AxiosError', code: 'ERR_BAD_RESPONSE', config: {…}, request: XMLHttpRequest, …}code: "ERR_BAD_RESPONSE"config: {transitional: {…}, adapter: Array(2), transformRequest: Array(1), transformResponse: Array(1), timeout: 0, …}message: "Request failed with status code 500"name: "AxiosError"request: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}response: {data: Blob, status: 500, statusText: 'INTERNAL SERVER ERROR', headers: n, config: {…}, …}stack: "AxiosError: Request failed with status code 500\n    at https://mentee-dev.herokuapp.com/static/js/main.0e0a4844.js:2:1152493\n    at XMLHttpRequest.d (https://mentee-dev.herokuapp.com/static/js/main.0e0a4844.js:2:1152641)"[[Prototype]]: Error
Promise.catch (async)
(anonymous) @ api.js:221
u @ regeneratorRuntime.js:44
(anonymous) @ regeneratorRuntime.js:125
(anonymous) @ regeneratorRuntime.js:69
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:22
(anonymous) @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:19
(anonymous) @ api.js:217
(anonymous) @ TrainingList.js:39
u @ regeneratorRuntime.js:44
(anonymous) @ regeneratorRuntime.js:125
(anonymous) @ regeneratorRuntime.js:69
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:22
(anonymous) @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:19
T @ button.js:197
Ie @ react-dom.production.min.js:54
ze @ react-dom.production.min.js:54
(anonymous) @ react-dom.production.min.js:55
Dr @ react-dom.production.min.js:105
Lr @ react-dom.production.min.js:106
(anonymous) @ react-dom.production.min.js:117
ul @ react-dom.production.min.js:274
Me @ react-dom.production.min.js:52
Ur @ react-dom.production.min.js:109
Kt @ react-dom.production.min.js:74
Wt @ react-dom.production.min.js:73
api.js:406 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'data')
    at ug (api.js:406:61)
    at TrainingList.js:40:19
    at u (regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (regeneratorRuntime.js:125:22)
    at Generator.next (regeneratorRuntime.js:69:21)
    at r (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:22:9)
```

**Comment by robert-dm** [comment]
<img width="1706" alt="image" src="https://user-images.githubusercontent.com/35821871/232351965-d579c0ea-3067-42c7-b587-7f30e56449b4.png">
